//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfflineCourseManager.Core.DB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public long IsFinished { get; set; }
        public long IsStarted { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string FullPath { get; set; }
    }
}
